### ISSUE TITLE
Rework meta file format

### ISSUE THREAD

**Issue by ashenoy463** [ashenoy463/mdx#4]
Reworks needed for xarray:

- Execution dates need to be extracted (through #5) 
- Current nested format is not supported by xarray

**Comment by ashenoy463** [comment]
Current file format is:

```yaml
Metadata:
  # Global ID for this sim (ideally 1 word)
  sim_id: "prelim"
  # Readable description
  sim_desc: "Preliminary run of 1 nanosecond at 300 K — test bed for refactoring and further processing code"
  # Dates yyyymmdd of chunk run start
  exec_date: [202401220710,202401241139,202401260443,202401270056]
  partition:
    # stepsize in real units
    step_fs: 0.5     
    # steps in a chunk
    chunk_size: 500000
    # number of chunks
    n_chunks: 40
  box:
    # number of atoms
    n_atoms: 49026

# real simtime = step_fs*chunk_size*n_chunks

```
